// Code generated by cmd/reset; DO NOT EDIT.

package storage

func (e *Event) Reset() {
	if e == nil {
		return
	}

	e.ShortURL = ""
	e.OriginalURL = ""
}

func (u *URLRecord) Reset() {
	if u == nil {
		return
	}

	u.ID = ""
	u.OriginURL = ""
}
