// Code generated by cmd/reset; DO NOT EDIT.

package handler

func (b *BatchRequest) Reset() {
	if b == nil {
		return
	}

	b.CorrelationID = ""
	b.OriginalURL = ""
}

func (b *BatchResponse) Reset() {
	if b == nil {
		return
	}

	b.CorrelationID = ""
	b.ShortURL = ""
}

func (r *RequestObject) Reset() {
	if r == nil {
		return
	}

	r.URL = ""
}

func (r *ResponseObject) Reset() {
	if r == nil {
		return
	}

	r.Result = ""
}
