package main

import (
	"os"
	"path/filepath"
	"testing"
)

// TestGenerate runs the generator end-to-end against the fixture module in
// testdata/src/example.com/sample and checks the resulting reset.gen.go
// against every rule from the assignment: primitives reset to their zero
// value, a slice truncates rather than going nil, a map is cleared, a
// pointer-to-string resets its pointee in place, a nested struct field
// (both by pointer and by value) delegates to its own Reset(), an
// unresettable field (a channel) is silently skipped, and a struct without
// the generate:reset marker gets no method at all.
func TestGenerate(t *testing.T) {
	dir, err := filepath.Abs("testdata/src/example.com/sample")
	if err != nil {
		t.Fatal(err)
	}
	genFile := filepath.Join(dir, "reset.gen.go")
	t.Cleanup(func() { os.Remove(genFile) })

	if err := generate(dir, []string{"./..."}); err != nil {
		t.Fatalf("generate: %v", err)
	}

	got, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatalf("reading generated file: %v", err)
	}

	const want = `// Code generated by cmd/reset; DO NOT EDIT.

package sample

func (c *Child) Reset() {
	if c == nil {
		return
	}

	c.Count = 0
}

func (r *Resettable) Reset() {
	if r == nil {
		return
	}

	r.I = 0
	r.Str = ""
	r.Flag = false
	if r.StrP != nil {
		*r.StrP = ""
	}
	r.S = r.S[:0]
	clear(r.M)
	if r.Child != nil {
		r.Child.Reset()
	}
	r.Value.Reset()
}

func (v *Value) Reset() {
	if v == nil {
		return
	}

	v.Label = ""
}
`

	if string(got) != want {
		t.Errorf("generated reset.gen.go mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// TestGenerate_NoMarker verifies that a package with no generate:reset
// annotations produces no reset.gen.go at all.
func TestGenerate_NoMarker(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/empty\n\ngo 1.26.2\n"), 0666); err != nil {
		t.Fatal(err)
	}
	src := "package empty\n\ntype Plain struct {\n\tX int\n}\n"
	if err := os.WriteFile(filepath.Join(dir, "plain.go"), []byte(src), 0666); err != nil {
		t.Fatal(err)
	}

	if err := generate(dir, []string{"./..."}); err != nil {
		t.Fatalf("generate: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "reset.gen.go")); !os.IsNotExist(err) {
		t.Fatalf("expected no reset.gen.go, stat returned err=%v", err)
	}
}
