// Code generated by cmd/reset; DO NOT EDIT.

package service

func (c *Claims) Reset() {
	if c == nil {
		return
	}

	c.UserID = ""
}

func (d *DeleteTask) Reset() {
	if d == nil {
		return
	}

	d.UserID = ""
	d.IDs = d.IDs[:0]
}
